dist: bionic

addons:
  apt:
    update: true

jobs:
  include:
    - stage: "Test"
      before_install:
        - sudo apt-get install docker.io
        - sudo docker --version
        - sudo usermod -aG docker $USER
        - sudo stat /etc/docker/daemon.json
        - sudo dockerd &
        - export DOCKER_CLI_EXPERIMENTAL=enabled
        - export DOCKER_BUILDKIT=1
        - docker build --platform=local -o . git://github.com/docker/buildx
        - mkdir -p ~/.docker/cli-plugins
        - mv buildx ~/.docker/cli-plugins/docker-buildx
        - docker buildx --help
      install:
        - true
      before_script:
        - true
      script:
        - true
