dist: bionic

services:
  - docker

addons:
  apt:
    update: true

jobs:
  include:
    - stage: "Test"
      before_install:
        #- sudo apt-get install docker.io
        #- sudo docker --version
        #- sudo usermod -aG docker $USER
        #- sudo stat /etc/docker/daemon.json
        #- sudo dockerd &
        #- export DOCKER_CLI_EXPERIMENTAL=enabled
        - bash ci/install_buildx.sh
        - docker buildx --help
      install:
        - true
      before_script:
        - true
      script:
        - true
