dist: bionic

addons:
  apt:
    update: true

jobs:
  include:
    - stage: "Test"
      before_install:
        - sudo apt-get install docker
        - sudo docker --version
      install:
        - true
      before_script:
        - true
      script:
        - true
